### ISSUE TITLE
HandsOnTable context menu options repeat

### ISSUE THREAD

**Issue by MaruthiGitHub** [ebertti/requery#13]
I am trying to use HandsOnTable in a web page designed using SAPUI5. I have an issue with the display of Context Menu. The options in the context menu repeat after the last option in the menu. I have included the code below and attached the screenshot of the Context Menu. Please help me resolve the issue.

    var container = document.getElementById('sheetContainer');

    var settingsHOT = {
      data: data,
      autoWrapRow: true,
      colHeaders: true,
      comments: false,
      contextMenu: {
        items: {
          "copy": {},
          "paste": {},
          "row_above": {},
          "row_below": {},
          "remove_row": {},
          "undo": {},
          "redo": {},
          "make_read_only": {},
          "alignment": {}
        }
      },
      contextMenuCopyPaste: {
        swfPath: "resources/ZeroClipboard.swf"
      },
      columns: [{}, {}, {}, {
        editor: 'select',
        selectOptions: ["Yes", "No", "Yes with exemptions"]
      }, {}, {
        renderer: 'html'
      }, {}, {}, {}, {}, {}],
      colWidths: [120, 100, 200, 150, 250, 250, 100, 250, 250, 250, 125],
      fixedColumnsLeft: 1,
      fixedRowsTop: 0,
      minRows: 1000,
      minCols: 26,
      maxRows: 10000,
      maxCols: 1000,
      minSpareRows: 5,
      manualColumnResize: true,
      manualRowResize: true,
      manualColumnMove: true,
      manualRowMove: true,
      mergeCells: false,
      persistentState: true,
      rowHeaders: true,
      removeRowPlugin: true,
      startRows: 5,
      startCols: 5,
      stretchH: 'none',
      search: true,
      wrodWrap: true
    };
![hotissue](https://cloud.githubusercontent.com/assets/5886000/6285593/720f0854-b923-11e4-833d-300559718f1d.png)

**Comment by ebertti** [comment]
Hi @MaruthiGitHub, This is not a repository of HandsOnTable, try this one:

https://github.com/handsontable/handsontable
